image: php:5.6.8

stages:
  - test
  - deploy

testing_testing:
  stage: test
  script: echo gcuerg

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=collaborative-project-esgi --api-key=$HEROKU_API_KEY
  only:
    - main
