version: "3.1"
services:

  mariadb:
    image: mariadb
    container_name: projet-mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root

  php:
    image: php:8.0.11-apache
    container_name: projet-php
    ports:
    - "8080:80"
    volumes:
      - /Users/matthieu/Documents/COURS IW4/SOLUTION DE VERSIONNING/Projet pédagogique/projet_collaboratif/:/var/www/html/
    depends_on:
      - composer
    env_file:
      - ./.env

  composer:
    image: composer:2.1.8
    container_name: projet-composer

